#!/bin/bash

[[ -n $1 ]] || { echo "enter output file" ; exit 1 ; }

nohup python ~/transformers/examples/run_squad.py \
    --model_type bert_uni_lstm_encoder_decoder \
    --model_name_or_path bert-base-uncased \
    --do_train \
    --do_eval \
    --do_lower_case \
    --train_file ~/transformers/squad-data/train-v2.0.json \
    --predict_file ~/transformers/squad-data/dev-v2.0.json \
    --learning_rate 3e-4 \
    --num_train_epochs 2 \
    --max_seq_length 384 \
    --doc_stride 128 \
    --output_dir ~/transformers/models/base_uncased_finetuned_squad_uni_lstm_encoder_decoder_lr_3e-4/ \
    --version_2_with_negative \
    --save_steps 1000 \
    --per_gpu_train_batch_size 12 \
    > "$1" 2>&1 &
